import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";
import { FaInstagram, FaFacebook, FaPhone, FaEnvelope, FaMapMarkerAlt } from "react-icons/fa";
import Image from "next/image";
import SessionWrapper from "./SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="tr">
      <body className="bg-white text-gray-900 min-h-screen flex flex-col">
        <SessionWrapper>
          <Navbar />
          <main className="flex-1 flex flex-col bg-gray-50">{children}</main>
          <footer className="w-full bg-gray-50 text-gray-700 pt-10 pb-6 mt-8 border-t border-gray-200">
            <div className="max-w-6xl mx-auto px-4">
              {/* Slogan ve Logo */}
              <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-8 gap-4">
                  <div className="flex items-center gap-6 flex-1 min-w-0">
                    <Image src="/logo.png/logo.png" alt="Atakum Belediyesi Logo" height={112} width={224} className="h-28 w-auto rounded-lg shadow bg-white p-2" />
                    <div className="flex flex-col items-start justify-center">
                      <div className="text-2xl md:text-3xl font-extrabold mb-1 pl-1 bg-gradient-to-r from-red-600 via-orange-400 to-yellow-400 bg-clip-text text-transparent">444 40 55</div>
                      <div className="text-4xl md:text-5xl font-extrabold whitespace-nowrap bg-gradient-to-r from-red-600 via-orange-400 to-yellow-400 bg-clip-text text-transparent">
                        #CanımAtakum
                      </div>
                    </div>
                  </div>
                {/* Sağ kısım: önce sosyal medya, altında iletişim */}
                <div className="flex-1 flex flex-col items-center md:items-end gap-2 text-sm">
                  <div className="flex items-center gap-4 mb-2">
                    <a href="https://instagram.com/hasanaliyucelgenclikmerkezi" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
                      <FaInstagram className="text-pink-500 text-2xl hover:scale-110 transition" />
                    </a>
                    <a href="https://facebook.com/hasanaliyucelgenclikmerkezi" target="_blank" rel="noopener noreferrer" aria-label="Facebook">
                      <FaFacebook className="text-blue-700 text-2xl hover:scale-110 transition" />
                    </a>
                  </div>
                  <div className="flex items-center gap-2"><FaPhone className="text-red-600" /> <span className="font-semibold">(501) 737 52 88</span></div>
                  <div className="flex items-center gap-2"><FaMapMarkerAlt className="text-green-600" /> Cumhuriyet, 37. Sk. No:5, 55200 Atakum/Samsun</div>
                  <div className="flex items-center gap-2"><FaEnvelope className="text-blue-600" /> bilgi@atakum.bel.tr</div>
                </div>
              </div>
              <div className="text-center text-xs text-gray-500 mt-6">
                © {new Date().getFullYear()} Atakum Belediyesi | Hasan Ali Yücel Gençlik Bilim ve Sanat Merkezi
              </div>
            </div>
          </footer>
        </SessionWrapper>
      </body>
    </html>
  )
}
